var Drivers = {
    Baby_Mario: "Baby Mario",
    Baby_Peach: "Baby Peach",
    Baby_Rosalina: "Baby Rosalina",
    Baby_Luigi: "Baby Luigi",
    Baby_Daisy: "Baby Daisy",
    Koopa_Troopa: "Koopa Troopa",
    Shy_Guy: "Shy Guy",
    Dry_Bones: "Dry Bones",
    Iggy: "Iggy",
    Larry: "Larry",
    Lemmy: "Lemmy",
    Ludwig: "Ludwig",
    Morton: "Morton",
    Roy: "Roy",
    Wendy: "Wendy",
    Mario: "Mario",
    Peach: "Peach",
    Yoshi: "Yoshi",
    Daisy: "Daisy",
    Toad: "Toad",
    Toadette: "Toadette",
    Rosalina: "Rosalina",
    Luigi: "Luigi",
    Toad_Pit_Crew: "Toad (Pit Crew)",
    Bowser: "Bowser",
    Donkey_Kong: "Donkey Kong",
    Diddy_Kong: "Diddy Kong",
    Lakitu: "Laktiu",
    Bowser_Jr: "Bowser Jr.",
    Wario: "Wario",
    Waluigi: "Waluigi",
    King_Boo: "King Boo",
    Metal_Mario: "Metal Mario",
    Peachette: "Peachette",
    Pauline: "Pauline",
    Mario_Musician: "Mario (Musician)",
    Peach_Kimono: "Peach (Kimono)",
    Mario_Hakama: "Mario (Hakama)",
    Rosalina_Halloween: "Rosalina (Halloween)",
    Peach_Vacation: "Peach (Vacation)",
    Dry_Bowser: "Dry Bowser",
    King_Boo_Luigis_Mansion: "King Boo (Luigi's Mansion)",
    Shy_Guy_Pastry_Chef: "Shy Guy (Pastry Chef)",
};

var Karts = {
    Pipe_Frame: "Pipe Frame",
    Birthday_Girl: "Birthday Girl",
    Mushmellow: "Mushmellow",
    Koopa_Dasher: "Koopa Dasher",
    Biddybuggy: "Biddybuggy",
    Blue_Biddybuggy: "Blue Biddybuggy",
    Cheep_Charger: "Cheep Charger",
    Pink_Mushmellow: "Pink Mushmellow",
    Bullet_Blaster: "Bullet Blaster",
    Bulls_Eye_Banzai: "Bull's-Eye Banzai",
    Landship: "Landship",
    Pipe_Buggy: "Pipe Buggy",
    Warship: "Warship",
    Mach_8: "Mach 8",
    Daytripper: "Daytripper",
    Turbo_Yoshi: "Turbo Yoshi",
    Soda_Jet: "Soda Jet",
    Super_Blooper: "Super Blooper",
    Gold_Blooper: "Gold Blooper",
    Royale: "Royale",
    Cloud_9: "Cloud 9",
    Poltergust_4000: "Poltergust 4000",
    Streamliner: "Streamliner",
    White_Royale: "White Royale",
    Flame_Flyer: "Flame Flyer",
    Barrel_Train: "Barrel Train",
    DK_Jumbo: "DK Jumbo",
    Chrome_DK_Jumbo: "Chrome DK Jumbo",
    Koopa_Clown: "Koopa Clown",
    Dark_Clown: "Dark Clown",
    B_Dasher: "B Dasher",
    Black_B_Dasher: "Black B Dasher",
    Yellow_Taxi: "Yellow Taxi",
    Quickshaw: "Quickshaw",
    Kabuki_Dasher: "Kabuki Dasher",
    Circuit_Special: "Circuit Special",
    Black_Circuit: "Black Circuit",
    Bumble_V: "Bumble V",
    Queen_Bee: "Queen Bee",
    Trickster: "Trickster",
    Ghost_Ride: "Ghost Ride",
    Macharon: "Macharon",
    Carrot_Kart: "Carrot Kart",
    Badwagon: "Badwagon",
    Blue_Badwagon: "Blue Badwagon",
    Gold_Train: "Gold Train",
};

var Chutes = {
    Super_Glider: "Super Glider",
    Parachute: "Parachute",
    Parafoil: "Parafoil",
    Paper_Glider: "Paper Glider",
    Droplet_Glider: "Droplet Glider",
    BBIA_Parafoil: "BBIA Parafoil",
    Piranha_Plant_Parafoil: "Piranha Plant Parafoil",
    Peach_Parasol: "Peach Parasol",
    Flower_Glider: "Flower Glider",
    Oilpaper_Umbrella: "Oilpaper Umbrella",
    Lightning_Oilpaper: "Lightning Oilpaper",
    Bob_omb_Parafoil: "Bob-omb Parafoil",
    Shell_Parachute: "Shell Parachute",
    Wario_Wing: "Wario Wing",
    Waluigi_Wing: "Waluigi Wing",
    BaNaNa_Parafoil: "BaNaNa Parafoil",
    Gold_Glider: "Gold Glider",
    Fare_Flier: "Fare Flier",
    Purple_Oilpaper_Umbrella: "Purple Oilpaper Umbrella",
    Full_Flight: "Full Flight",
    Strawberry_Crepe: "Strawberry Crepe",
    Le_Tricolore: "Le Tricolore",
    Swooper: "Swooper",
    Bullet_Bill_Parachute: "Bullet Bill Parachute",
    Cloud_Glider: "Cloud Glider",
    Rainy_Balloons: "Rainy Balloons",
    Wicked_Wings: "Wicked Wings",
};

var Courses = {
    Mario_Circuit_1: 0,
    Mario_Circuit_1T: 1,
    Mario_Circuit_1R: 2,
    Mario_Circuit_2: 3,
    Mario_Circuit_2T: 4,
    Mario_Circuit_2R: 5,
    Mario_Circuit_3: 6,
    Mario_Circuit_3T: 7,
    Mario_Circuit_3R: 8,
    Choco_Island_2: 9,
    Choco_Island_2T: 10,
    Choco_Island_2R: 11,
    Koopa_Troopa_Beach: 12,
    Koopa_Troopa_Beach_T: 13,
    Koopa_Troopa_Beach_R: 14,
    Bowsers_Castle_1: 15,
    Bowsers_Castle_1T: 16,
    Bowsers_Castle_1R: 17,
    Dino_Dino_Jungle: 18,
    Dino_Dino_Jungle_T: 19,
    Dino_Dino_Jungle_R: 20,
    Yoshi_Circuit: 21,
    Yoshi_Circuit_T: 22,
    Yoshi_Circuit_R: 23,
    Luigis_Mansion: 24,
    Luigis_Mansion_T: 25,
    Luigis_Mansion_R: 26,
    Waluigi_Pinball: 27,
    Waluigi_Pinball_T: 28,
    Waluigi_Pinball_R: 29,
    DK_Pass: 30,
    DK_Pass_T: 31,
    DK_Pass_R: 32,
    Cheep_Cheep_Lagoon: 33,
    Cheep_Cheep_Lagoon_T: 34,
    Cheep_Cheep_Lagoon_R: 35,
    Toad_Circuit: 36,
    Toad_Circuit_T: 37,
    Toad_Circuit_R: 38,
    Rock_Rock_Mountain: 39,
    Rock_Rock_Mountain_T: 40,
    Rock_Rock_Mountain_R: 41,
    Daisy_Hills: 42,
    Daisy_Hills_T: 43,
    Daisy_Hills_R: 44,
    Shy_Guy_Bazaar: 45,
    Shy_Guy_Bazaar_T: 46,
    Shy_Guy_Bazaar_R: 47,
    Mario_Circuit: 48,
    Mario_Circuit_T: 49,
    Mario_Circuit_R: 50,
    Rainbow_Road: 51,
    Rainbow_Road_T: 52,
    Rainbow_Road_R: 53,
    Kalimari_Desert: 54,
    Kalimari_Desert_T: 55,
    Kalimari_Desert_R: 56,
    Neo_Bowser_City: 57,
    Neo_Bowser_City_T: 58,
    Neo_Bowser_City_R: 59,
    Ghost_Valley_1: 60,
    Ghost_Valley_1T: 61,
    Ghost_Valley_1R: 62,
    Tokyo_Blur: 63,
    Tokyo_Blur_T: 64,
    Tokyo_Blur_R: 65,
    Tokyo_Blur_RT: 66,
    Paris_Promenade: 67,
    Paris_Promenade_T: 68,
    Paris_Promenade_R: 69,
    Paris_Promenade_RT: 70,
    New_York_Minute: 71,
    New_York_Minute_T: 72,
    New_York_Minute_R: 73,
    New_York_Minute_RT: 74,
    None: 1000,
};

class Item {
    item;
    courses3;
    courses2;
    constructor(item, courses3, courses2) {
        this.item = item;
        this.courses3 = courses3;
        this.courses2 = courses2;
    }
}

var drivers = [
    new Item(Drivers.Baby_Mario,
        [Courses.Mario_Circuit_1T,
         Courses.Waluigi_Pinball],
        [Courses.Daisy_Hills_R,
         Courses.Waluigi_Pinball_T,
         Courses.Yoshi_Circuit,
         Courses.Toad_Circuit,
         Courses.Toad_Circuit_T,
         Courses.Koopa_Troopa_Beach]),
    new Item(Drivers.Baby_Peach,
        [Courses.Cheep_Cheep_Lagoon],
        [Courses.Mario_Circuit_1R,
         Courses.Choco_Island_2,
         Courses.Daisy_Hills_R,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Ghost_Valley_1,
         Courses.Tokyo_Blur,
         Courses.Tokyo_Blur_T]),
    new Item(Drivers.Baby_Daisy,
        [Courses.Daisy_Hills_T],
        [Courses.Daisy_Hills_R,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Kalimari_Desert_T,
         Courses.Toad_Circuit_R,
         Courses.Mario_Circuit_1R,
         Courses.Cheep_Cheep_Lagoon,
         Courses.Choco_Island_2R,
         Courses.Shy_Guy_Bazaar,
         Courses.Toad_Circuit_RT]),
    new Item(Drivers.Baby_Rosalina,
        [Courses.Choco_Island_2T,
         Courses.Rainbow_Road_T],
        [Courses.Yoshi_Circuit_R,
         Courses.Luigis_Mansion_T,
         Courses.Mario_Circuit_2T,
         Courses.Rainbow_Road_R,
         Courses.Ghost_Valley_1]),
    new Item(Drivers.Baby_Luigi,
        [Courses.Luigis_Mansion_R],
        [Courses.Mario_Circuit_1R,
         Courses.Luigis_Mansion,
         Courses.Waluigi_Pinball,
         Courses.Daisy_Hills_T]),
    new Item(Drivers.Koopa_Troopa,
        [Courses.Koopa_Troopa_Beach],
        [Courses.Bowsers_Castle_1T,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Mario_Circuit_T,
         Courses.Cheep_Cheep_Lagoon,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.Choco_Island_2,
         Courses.Tokyo_Blur_R]),
    new Item(Drivers.Shy_Guy,
        [Courses.Shy_Guy_Bazaar],
        [Courses.Dino_Dino_Jungle,
         Courses.Bowsers_Castle_1,
         Courses.Bowsers_Castle_1R,
         Courses.Rainbow_Road,
         Courses.Shy_Guy_Bazaar_T,
         Courses.Rainbow_Road,
         Courses.Ghost_Valley_1R]),
    new Item(Drivers.Dry_Bones,
        [Courses.Bowsers_Castle_1T,
         Courses.Shy_Guy_Bazaar_T],
        [Courses.Cheep_Cheep_Lagoon_R,
         Courses.Cheep_Cheep_Lagoon_T,
         Courses.Bowsers_Castle_1,
         Courses.Bowsers_Castle_1R,
         Courses.Choco_Island_2T,
         Courses.Kalimari_Desert]),
    new Item(Drivers.Iggy,
        [Courses.Choco_Island_2R],
        [Courses.Bowsers_Castle_1T,
         Courses.Paris_Promenade_T,
         Courses.Rock_Rock_Mountain_T,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Kalimari_Desert_R,
         Courses.Mario_Circuit_2,
         Courses.Mario_Circuit_2R,
         Courses.Neo_Bowser_City_T,
         Courses.Ghost_Valley_1T]),
    new Item(Drivers.Larry,
        [Courses.Kalimari_Desert_R],
        [Courses.Cheep_Cheep_Lagoon_R,
         Courses.Mario_Circuit_3T,
         Courses.Paris_Promenade_R,
         Courses.Paris_Promenade_RT,
         Courses.Rock_Rock_Mountain_T,
         Courses.Kalimari_Desert_T,
         Courses.Neo_Bowser_City,
         Courses.Neo_Bowser_City_T]),
    new Item(Drivers.Lemmy,
        [Courses.Cheep_Cheep_Lagoon_R,
         Courses.Mario_Circuit_2T,
         Courses.Rainbow_Road_R],
        [Courses.Bowsers_Castle_1,
         Courses.Choco_Island_2T,
         Courses.Toad_Circuit_R,
         Courses.Rainbow_Road]),
    new Item(Drivers.Ludwig,
        [Courses.Bowsers_Castle_1,
         Courses.Kalimari_Desert],
        [Courses.Rainbow_Road,
         Courses.Shy_Guy_Bazaar_R]),
    new Item(Drivers.Morton,
        [Courses.Kalimari_Desert],
        [Courses.Bowsers_Castle_1,
         Courses.Rock_Rock_Mountain,
         Courses.Kalimari_Desert_T,
         Courses.Mario_Circuit_2R,
         Courses.Neo_Bowser_City_T]),
    new Item(Drivers.Roy,
        [Courses.Kalimari_Desert_T],
        [Courses.Kalimari_Desert,
         Courses.Kalimari_Desert_R,
         Courses.Mario_Circuit_2T,
         Courses.Neo_Bowser_City_R,
         Courses.Dino_Dino_Jungle_R,
         Courses.Koopa_Troopa_Beach_T]),
    new Item(Drivers.Wendy,
        [Courses.Choco_Island_2],
        [Courses.Cheep_Cheep_Lagoon_R,
         Courses.Daisy_Hills_T,
         Courses.Mario_Circuit,
         Courses.Mario_Circuit_T,
         Courses.Neo_Bowser_City_R]),
    new Item(Drivers.Mario,
        [Courses.Mario_Circuit_1,
         Courses.Cheep_Cheep_Lagoon_T,
         Courses.Koopa_Troopa_Beach,
         Courses.Mario_Circuit_T],
        [Courses.Mario_Circuit_1R,
         Courses.Yoshi_Circuit,
         Courses.Yoshi_Circuit_R,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Koopa_Troopa_Beach_R]),
    new Item(Drivers.Peach,
        [Courses.Mario_Circuit_1T,
         Courses.Yoshi_Circuit_R,
         Courses.Luigis_Mansion_R,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Koopa_Troopa_Beach_T],
        [Courses.Mario_Circuit_1R,
         Courses.Cheep_Cheep_Lagoon_T,
         Courses.Shy_Guy_Bazaar,
         Courses.Paris_Promenade,
         Courses.Toad_Circuit_T,
         Courses.Mario_Circuit,
         Courses.Mario_Circuit_R]),
    new Item(Drivers.Yoshi,
        [Courses.Yoshi_Circuit,
         Courses.Yoshi_Circuit_T,
         Courses.Rock_Rock_Mountain],
        [Courses.Yoshi_Circuit_R,
         Courses.Dino_Dino_Jungle,
         Courses.Dino_Dino_Jungle_R]),
    new Item(Drivers.Daisy,
        [Courses.Cheep_Cheep_Lagoon_R,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Daisy_Hills,
         Courses.Daisy_Hills_T],
        [Courses.Yoshi_Circuit_T,
         Courses.Shy_Guy_Bazaar_T,
         Courses.Toad_Circuit,
         Courses.Mario_Circuit_T,
         Courses.Paris_Promenade_R]),
    new Item(Drivers.Toad,
        [Courses.Toad_Circuit,
         Courses.Rock_Rock_Mountain_T,
         Courses.Mario_Circuit_R],
        [Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_1T,
         Courses.Luigis_Mansion,
         Courses.Paris_Promenade_R,
         Courses.Toad_Circuit_T,
         Courses.Koopa_Troopa_Beach,
         Courses.Ghost_Valley_1,
         Courses.Ghost_Valley_1R]),
    new Item(Drivers.Toadette,
        [Courses.Mario_Circuit_3R,
         Courses.Toad_Circuit,
         Courses.Daisy_Hills_R],
        [Courses.Mario_Circuit_3,
         Courses.Paris_Promenade,
         Courses.Toad_Circuit_R,
         Courses.Toad_Circuit_T,
         Courses.Daisy_Hills,
         Courses.Koopa_Troopa_Beach,
         Courses.Mario_Circuit,
         Courses.Mario_Circuit_T]),
    new Item(Drivers.Rosalina,
        [Courses.Cheep_Cheep_Lagoon,
         Courses.Mario_Circuit_R,
         Courses.Rainbow_Road,
         Courses.Paris_Promenade_RT],
        [Courses.Choco_Island_2R,
         Courses.Mario_Circuit_3T,
         Courses.Mario_Circuit_2,
         Courses.Neo_Bowser_City_R,
         Courses.Rainbow_Road_R,
         Courses.Paris_Promenade_R]),
    new Item(Drivers.Luigi,
        [Courses.Cheep_Cheep_Lagoon_T,
         Courses.Luigis_Mansion,
         Courses.Luigis_Mansion_T,
         Courses.Ghost_Valley_1],
        [Courses.Luigis_Mansion_R,
         Courses.Waluigi_Pinball_R]),
    new Item(Drivers.Toad_Pit_Crew,
        [Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_3],
        [Courses.Yoshi_Circuit,
         Courses.Mario_Circuit_3T,
         Courses.Toad_Circuit,
         Courses.Toad_Circuit_T,
         Courses.Paris_Promenade_T]),
    new Item(Drivers.Bowser,
        [Courses.Dino_Dino_Jungle_T,
         Courses.Bowsers_Castle_1,
         Courses.Bowsers_Castle_1T,
         Courses.Neo_Bowser_City],
        [Courses.Bowsers_Castle_1R,
         Courses.Kalimari_Desert,
         Courses.Rainbow_Road_T,
         Courses.Rock_Rock_Mountain_R,
         Courses.New_York_Minute_T]),
    new Item(Drivers.Donkey_Kong,
        [Courses.Dino_Dino_Jungle,
         Courses.Waluigi_Pinball_R,
         Courses.Rock_Rock_Mountain],
        [Courses.Dino_Dino_Jungle_R,
         Courses.Dino_Dino_Jungle_T,
         Courses.Rock_Rock_Mountain_R,
         Courses.Koopa_Troopa_Beach_R,
         Courses.New_York_Minute,
         Courses.New_York_Minute_T,
         Courses.Tokyo_Blur_R]),
    new Item(Drivers.Diddy_Kong,
        [Courses.Dino_Dino_Jungle_R,
         Courses.Toad_Circuit_R,
         Courses.Rock_Rock_Mountain_R],
        [Courses.Choco_Island_2T,
         Courses.Waluigi_Pinball_R,
         Courses.Mario_Circuit_3,
         Courses.Rock_Rock_Mountain,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Koopa_Troopa_Beach_T,
         Courses.New_York_Minute_R,
         Courses.New_York_Minute_RT,
         Courses.Tokyo_Blur_RT]),
    new Item(Drivers.Lakitu,
        [Courses.Waluigi_Pinball_T,
         Courses.Toad_Circuit_T,
         Courses.Paris_Promenade_T,
         Courses.Mario_Circuit_2T,
         Courses.Mario_Circuit_3T,
         Courses.Ghost_Valley_1T],
        [Courses.Cheep_Cheep_Lagoon,
         Courses.Dino_Dino_Jungle_R,
         Courses.Rock_Rock_Mountain_R,
         Courses.Mario_Circuit_2,
         Courses.New_York_Minute_RT,
         Courses.Tokyo_Blur,
         Courses.Tokyo_Blur_T]),
    new Item(Drivers.Bowser_Jr,
        [Courses.Bowsers_Castle_1R,
         Courses.Choco_Island_2R,
         Courses.Neo_Bowser_City,
         Courses.Neo_Bowser_City_T,
         Courses.Paris_Promenade_T],
        [Courses.Cheep_Cheep_Lagoon,
         Courses.Bowsers_Castle_1T,
         Courses.Mario_Circuit_2T,
         Courses.Neo_Bowser_City_R]),
    new Item(Drivers.Wario,
        [Courses.Choco_Island_2T,
         Courses.Kalimari_Desert_R,
         Courses.Kalimari_Desert_T],
        [Courses.Dino_Dino_Jungle_T,
         Courses.Choco_Island_2,
         Courses.Rock_Rock_Mountain_T,
         Courses.Mario_Circuit_3,
         Courses.Mario_Circuit_3R,
         Courses.Neo_Bowser_City,
         Courses.New_York_Minute_R]),
    new Item(Drivers.Waluigi,
        [Courses.Waluigi_Pinball,
         Courses.Rock_Rock_Mountain,
         Courses.Neo_Bowser_City_R],
        [Courses.Waluigi_Pinball_R,
         Courses.Waluigi_Pinball_T,
         Courses.Kalimari_Desert,
         Courses.Paris_Promenade]),
    new Item(Drivers.King_Boo,
        [Courses.Shy_Guy_Bazaar,
         Courses.Luigis_Mansion,
         Courses.Ghost_Valley_1R],
        [Courses.Choco_Island_2T,
         Courses.Waluigi_Pinball,
         Courses.Ghost_Valley_1,
         Courses.Ghost_Valley_1T,
         Courses.Paris_Promenade_T]),
    new Item(Drivers.Metal_Mario,
        [Courses.Shy_Guy_Bazaar,
         Courses.Rock_Rock_Mountain_R,
         Courses.Mario_Circuit_2R,
         Courses.Rainbow_Road,
         Courses.Rainbow_Road_T],
        [Courses.Mario_Circuit_1T,
         Courses.Yoshi_Circuit_R,
         Courses.Yoshi_Circuit_T,
         Courses.Dino_Dino_Jungle_T,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Shy_Guy_Bazaar_T,
         Courses.Waluigi_Pinball,
         Courses.Toad_Circuit,
         Courses.Rainbow_Road_R]),
    new Item(Drivers.Peachette,
        [Courses.Dino_Dino_Jungle_R,
         Courses.Waluigi_Pinball_T,
         Courses.Toad_Circuit,
         Courses.Toad_Circuit_T,
         Courses.Mario_Circuit],
        [Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_1R,
         Courses.Yoshi_Circuit,
         Courses.Yoshi_Circuit_T,
         Courses.Luigis_Mansion,
         Courses.Mario_Circuit_3,
         Courses.Daisy_Hills,
         Courses.Mario_Circuit_R,
         Courses.Rainbow_Road_R]),
    new Item(Drivers.Pauline,
        [Courses.Luigis_Mansion_R,
         Courses.Waluigi_Pinball_T,
         Courses.New_York_Minute,
         Courses.New_York_Minute_RT],
        [Courses.Cheep_Cheep_Lagoon_T,
         Courses.Yoshi_Circuit_T,
         Courses.Shy_Guy_Bazaar,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Luigis_Mansion_T,
         Courses.Neo_Bowser_City,
         Courses.New_York_Minute_T,
         Courses.New_York_Minute_R]),
    new Item(Drivers.Mario_Musician,
        [Courses.Yoshi_Circuit_R,
         Courses.Waluigi_Pinball_R,
         Courses.Mario_Circuit_3,
         Courses.Daisy_Hills,
         Courses.New_York_Minute_T,
         Courses.New_York_Minute_R],
        [Courses.Luigis_Mansion,
         Courses.Mario_Circuit_3R,
         Courses.Rock_Rock_Mountain_T,
         Courses.Daisy_Hills_R,
         Courses.Mario_Circuit_T,
         Courses.Neo_Bowser_City_T,
         Courses.Rainbow_Road_T,
         Courses.New_York_Minute,
         Courses.New_York_Minute_RT,
         Courses.Paris_Promenade_RT]),
    new Item(Drivers.Peach_Kimono,
        [Courses.Waluigi_Pinball,
         Courses.Mario_Circuit_3T,
         Courses.Daisy_Hills_R,
         Courses.Mario_Circuit_2R,
         Courses.Mario_Circuit,
         Courses.Tokyo_Blur_R,
         Courses.Tokyo_Blur_T],
        [Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_R,
         Courses.Rainbow_Road,
         Courses.Tokyo_Blur,
         Courses.Tokyo_Blur_RT,
         Courses.Paris_Promenade_T]),
    new Item(Drivers.Mario_Hakama,
        [Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_1T,
         Courses.Bowsers_Castle_1T,
         Courses.Mario_Circuit_2,
         Courses.Mario_Circuit_T,
         Courses.Tokyo_Blur,
         Courses.Tokyo_Blur_RT],
        [Courses.Mario_Circuit_1R,
         Courses.Dino_Dino_Jungle_R,
         Courses.Bowsers_Castle_1R,
         Courses.Shy_Guy_Bazaar_T,
         Courses.Waluigi_Pinball,
         Courses.Mario_Circuit_2T,
         Courses.Rainbow_Road_T,
         Courses.Ghost_Valley_1T,
         Courses.Tokyo_Blur_T]),
    new Item(Drivers.Rosalina_Halloween,
        [Courses.Shy_Guy_Bazaar,
         Courses.Choco_Island_2,
         Courses.Luigis_Mansion,
         Courses.Ghost_Valley_1,
         Courses.Ghost_Valley_1T],
        [Courses.Neo_Bowser_City,
         Courses.Rainbow_Road,
         Courses.Rainbow_Road_R,
         Courses.Rainbow_Road_T,
         Courses.Ghost_Valley_1R,
         Courses.Paris_Promenade,
         Courses.Paris_Promenade_R]),
    new Item(Drivers.Peach_Vacation,
        [Courses.Mario_Circuit_1R,
         Courses.Mario_Circuit_3,
         Courses.Toad_Circuit_R,
         Courses.Paris_Promenade_RT,
         Courses.Toad_Circuit_R,
         Courses.Koopa_Troopa_Beach,
         Courses.Koopa_Troopa_Beach_T],
        [Courses.Mario_Circuit_1,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.Mario_Circuit_3R]),
    new Item(Drivers.Dry_Bowser,
        [Courses.Dino_Dino_Jungle,
         Courses.Dino_Dino_Jungle_T,
         Courses.Bowsers_Castle_1R,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Neo_Bowser_City_T],
        [Courses.Bowsers_Castle_1,
         Courses.Rock_Rock_Mountain,
         Courses.Rock_Rock_Mountain_T,
         Courses.Daisy_Hills_T,
         Courses.Kalimari_Desert_T,
         Courses.Neo_Bowser_City,
         Courses.Neo_Bowser_City_R]),
    new Item(Drivers.King_Boo_Luigis_Mansion,
        [Courses.Bowsers_Castle_1,
         Courses.Shy_Guy_Bazaar_T,
         Courses.Luigis_Mansion_T,
         Courses.Rock_Rock_Mountain_T,
         Courses.Ghost_Valley_1,
         Courses.Ghost_Valley_1R],
        [Courses.Yoshi_Circuit,
         Courses.Yoshi_Circuit_T,
         Courses.Luigis_Mansion_R,
         Courses.Ghost_Valley_1T]),
    new Item(Drivers.Shy_Guy_Pastry_Chef,
        [Courses.Shy_Guy_Bazaar_R,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Kalimari_Desert,
         Courses.Neo_Bowser_City_R,
         Courses.Paris_Promenade_R,
         Courses.Paris_Promenade_T],
        [Courses.Shy_Guy_Bazaar,
         Courses.Choco_Island_2R,
         Courses.Rock_Rock_Mountain_T,
         Courses.Paris_Promenade,
         Courses.Paris_Promenade_RT])
]
var karts = [
    new Item(Karts.Pipe_Frame,
        [Courses.Mario_Circuit_1R],
        [Courses.Dino_Dino_Jungle,
         Courses.Koopa_Troopa_Beach,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Toad_Circuit_T,
         Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_2]),
    new Item(Karts.Birthday_Girl,
        [Courses.Daisy_Hills_R,
         Courses.Toad_Circuit_T,
         Courses.Choco_Island_2T],
        [Courses.Daisy_Hills,
         Courses.Daisy_Hills_T,
         Courses.Mario_Circuit_R,
         Courses.Yoshi_Circuit_T]),
    new Item(Karts.Mushmellow,
        [Courses.Toad_Circuit,
         Courses.Toad_Circuit_T],
        [Courses.Cheep_Cheep_Lagoon_R,
         Courses.Mario_Circuit_3T,
         Courses.Toad_Circuit_R,
         Courses.Daisy_Hills]),
    new Item(Karts.Kabuki_Dasher,
        [Courses.Koopa_Troopa_Beach],
        [Courses.Dino_Dino_Jungle_T,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Kalimari_Desert_T,
         Courses.Mario_Circuit_2R,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.Cheep_Cheep_Lagoon_T,
         Courses.Choco_Island_2R,
         Courses.Shy_Guy_Bazaar_R]),
    new Item(Karts.Biddybuggy,
        [Courses.Choco_Island_2,
         Courses.Koopa_Troopa_Beach_T],
        [Courses.Toad_Circuit_R,
         Courses.Mario_Circuit,
         Courses.Mario_Circuit_T,
         Courses.Choco_Island_2T,
         Courses.Tokyo_Blur,
         Courses.Cheep_Cheep_Lagoon_T]),
    new Item(Karts.Blue_Biddybuggy,
        [Courses.Kalimari_Desert_T,
         Courses.Mario_Circuit_2R],
        [Courses.Ghost_Valley_1T,
         Courses.Toad_Circuit,
         Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_2,
         Courses.Mario_Circuit_2T,
         Courses.Cheep_Cheep_Lagoon,
         Courses.Choco_Island_2R,
         Courses.Tokyo_Blur,
         Courses.Tokyo_Blur_T]),
    new Item(Karts.Cheep_Charger,
        [Courses.Koopa_Troopa_Beach_R,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.Choco_Island_2R],
        [Courses.Koopa_Troopa_Beach,
         Courses.Rainbow_Road_R,
         Courses.Mario_Circuit_1R,
         Courses.Mario_Circuit_2T,
         Courses.Cheep_Cheep_Lagoon,
         Courses.Choco_Island_2]),
    new Item(Karts.Pink_Mushmellow,
        [Courses.Mario_Circuit_3R],
        [Courses.Mario_Circuit_3,
         Courses.Rock_Rock_Mountain_R,
         Courses.Paris_Promenade_RT]),
    new Item(Karts.Bullet_Blaster,
        [Courses.Shy_Guy_Bazaar_T,
         Courses.Bowsers_Castle_1],
        [Courses.Rock_Rock_Mountain_R,
         Courses.Kalimari_Desert,
         Courses.Neo_Bowser_City,
         Courses.Shy_Guy_Bazaar,
         Courses.Bowsers_Castle_1R]),
    new Item(Karts.Bulls_Eye_Banzai,
        [Courses.Bowsers_Castle_1T,
         Courses.New_York_Minute_T],
        [Courses.Rock_Rock_Mountain,
         Courses.Rainbow_Road,
         Courses.Shy_Guy_Bazaar,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Shy_Guy_Bazaar_T,
         Courses.Bowsers_Castle_1,
         Courses.Bowsers_Castle_1R]),
    new Item(Karts.Landship,
        [Courses.Bowsers_Castle_1R,
         Courses.Kalimari_Desert_R,
         Courses.Kalimari_Desert_T],
        [Courses.Bowsers_Castle_1,
         Courses.Neo_Bowser_City_R]),
    new Item(Karts.Pipe_Buggy,
        [Courses.Waluigi_Pinball_R],
        [Courses.Dino_Dino_Jungle_R,
         Courses.Dino_Dino_Jungle_T,
         Courses.Waluigi_Pinball,
         Courses.Waluigi_Pinball_T]),
    new Item(Karts.Warship,
        [Courses.Neo_Bowser_City_R,
         Courses.Ghost_Valley_1R],
        [Courses.Bowsers_Castle_1,
         Courses.Luigis_Mansion,
         Courses.Kalimari_Desert,
         Courses.Ghost_Valley_1]),
    new Item(Karts.Mach_8,
        [Courses.Mario_Circuit_1,
         Courses.Yoshi_Circuit_R,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Rock_Rock_Mountain_T],
        [Courses.Yoshi_Circuit,
         Courses.Yoshi_Circuit_T,
         Courses.Luigis_Mansion_T,
         Courses.Waluigi_Pinball,
         Courses.Toad_Circuit,
         Courses.Toad_Circuit_T]),
    new Item(Karts.Daytripper,
        [Courses.Shy_Guy_Bazaar_R,
         Courses.Daisy_Hills,
         Courses.Mario_Circuit_2],
        [Courses.Mario_Circuit_1T,
         Courses.Paris_Promenade_T,
         Courses.Toad_Circuit_R,
         Courses.Daisy_Hills_T,
         Courses.Mario_Circuit,
         Courses.Rainbow_Road,
         Courses.Rainbow_Road_T,
         Courses.New_York_Minute]),
    new Item(Karts.Turbo_Yoshi,
        [Courses.Yoshi_Circuit,
         Courses.Mario_Circuit_1T,
         Courses.Dino_Dino_Jungle_T],
        [Courses.Toad_Circuit_R,
         Courses.Rock_Rock_Mountain,
         Courses.Yoshi_Circuit_R,
         Courses.Daisy_Hills,
         Courses.Dino_Dino_Jungle,
         Courses.Dino_Dino_Jungle_R]),
    new Item(Karts.Soda_Jet,
        [Courses.Koopa_Troopa_Beach_T,
         Courses.Cheep_Cheep_Lagoon,
         Courses.New_York_Minute,
         Courses.Tokyo_Blur],
        [Courses.Koopa_Troopa_Beach,
         Courses.Rock_Rock_Mountain_T,
         Courses.Yoshi_Circuit_T,
         Courses.Mario_Circuit_1R,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.Tokyo_Blur_T]),
    new Item(Karts.Super_Blooper,
        [Courses.Koopa_Troopa_Beach_R,
         Courses.Mario_Circuit_2R,
         Courses.Cheep_Cheep_Lagoon,
         Courses.Cheep_Cheep_Lagoon_T],
        [Courses.Bowsers_Castle_1T,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Neo_Bowser_City,
         Courses.Toad_Circuit,
         Courses.Yoshi_Circuit,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.Choco_Island_2]),
    new Item(Karts.Gold_Blooper,
        [Courses.Koopa_Troopa_Beach,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Mario_Circuit_1R,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.Shy_Guy_Bazaar,
         Courses.New_York_Minute_R],
        [Courses.Koopa_Troopa_Beach_R,
         Courses.Rainbow_Road,
         Courses.Rainbow_Road_T,
         Courses.Yoshi_Circuit_R,
         Courses.Cheep_Cheep_Lagoon,
         Courses.Cheep_Cheep_Lagoon_T]),
    new Item(Karts.Royale,
        [Courses.Choco_Island_2,
         Courses.Mario_Circuit_R,
         Courses.Rainbow_Road_T],
        [Courses.Mario_Circuit_1R,
         Courses.Yoshi_Circuit,
         Courses.Toad_Circuit_R,
         Courses.Toad_Circuit_T,
         Courses.Daisy_Hills,
         Courses.Daisy_Hills_R,
         Courses.Mario_Circuit]),
    new Item(Karts.Cloud_9,
        [Courses.Rainbow_Road,
         Courses.Tokyo_Blur_T],
        [Courses.Cheep_Cheep_Lagoon,
         Courses.Shy_Guy_Bazaar_T,
         Courses.Kalimari_Desert_R,
         Courses.Mario_Circuit_2,
         Courses.Neo_Bowser_City_R,
         Courses.Tokyo_Blur_RT,
         Courses.Paris_Promenade_RT]),
    new Item(Karts.Poltergust_4000,
        [Courses.Luigis_Mansion_R,
         Courses.Ghost_Valley_1],
        [Courses.Koopa_Troopa_Beach,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Luigis_Mansion_T,
         Courses.Ghost_Valley_1R,
         Courses.Waluigi_Pinball]),
    new Item(Karts.Streamliner,
        [Courses.Mario_Circuit_3,
         Courses.Mario_Circuit_3T],
        [Courses.Mario_Circuit_3R,
         Courses.Paris_Promenade]),
    new Item(Karts.White_Royale,
        [Courses.Luigis_Mansion,
         Courses.Luigis_Mansion_T,
         Courses.Paris_Promenade_R,
         Courses.Rock_Rock_Mountain],
        [Courses.Mario_Circuit_3T,
         Courses.Paris_Promenade,
         Courses.Paris_Promenade_RT]),
    new Item(Karts.Flame_Flyer,
        [Courses.Dino_Dino_Jungle,
         Courses.Bowsers_Castle_1T],
        [Courses.Dino_Dino_Jungle_R,
         Courses.Shy_Guy_Bazaar,
         Courses.Rock_Rock_Mountain_R,
         Courses.Daisy_Hills_T,
         Courses.Neo_Bowser_City_T,
         Courses.New_York_Minute_T,
         Courses.New_York_Minute_R,
         Courses.New_York_Minute_RT]),
    new Item(Karts.Barrel_Train,
        [Courses.Rock_Rock_Mountain,
         Courses.Rock_Rock_Mountain_R,
         Courses.Kalimari_Desert_T,
         Courses.Dino_Dino_Jungle_R],
        [Courses.Rock_Rock_Mountain_T,
         Courses.Kalimari_Desert_R,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Dino_Dino_Jungle,
         Courses.Koopa_Troopa_Beach_R,
         Courses.New_York_Minute]),
    new Item(Karts.DK_Jumbo,
        [Courses.Dino_Dino_Jungle,
         Courses.Kalimari_Desert,
         Courses.Rock_Rock_Mountain,
         Courses.Rock_Rock_Mountain_T,
         Courses.Choco_Island_2R],
        [Courses.Dino_Dino_Jungle_R,
         Courses.Dino_Dino_Jungle_T,
         Courses.Kalimari_Desert_T,
         Courses.Rock_Rock_Mountain_R,
         Courses.Choco_Island_2T]),
    new Item(Karts.Chrome_DK_Jumbo,
        [Courses.Dino_Dino_Jungle_T,
         Courses.Kalimari_Desert_R,
         Courses.Tokyo_Blur_RT],
        [Courses.Bowsers_Castle_1R,
         Courses.Rock_Rock_Mountain_R,
         Courses.Daisy_Hills_R,
         Courses.Kalimari_Desert,
         Courses.Kalimari_Desert_T,
         Courses.Tokyo_Blur_R,
         Courses.Tokyo_Blur_T,
         Courses.Paris_Promenade_R]),
    new Item(Karts.Koopa_Clown,
        [Courses.Neo_Bowser_City,
         Courses.Rainbow_Road_R],
        [Courses.Bowsers_Castle_1,
         Courses.Bowsers_Castle_1R,
         Courses.Bowsers_Castle_1T,
         Courses.Kalimari_Desert_R,
         Courses.Neo_Bowser_City_R,
         Courses.Neo_Bowser_City_T]),
    new Item(Karts.Dark_Clown,
        [Courses.Bowsers_Castle_1R,
         Courses.Waluigi_Pinball],
        [Courses.Bowsers_Castle_1T,
         Courses.Waluigi_Pinball_R,
         Courses.Waluigi_Pinball_T,
         Courses.Rock_Rock_Mountain_T,
         Courses.Neo_Bowser_City,
         Courses.Neo_Bowser_City_R]),
    new Item(Karts.B_Dasher,
        [Courses.Daisy_Hills,
         Courses.Mario_Circuit,
         Courses.Toad_Circuit,
         Courses.Toad_Circuit_R,
         Courses.Mario_Circuit_1,
         Courses.Cheep_Cheep_Lagoon_T],
        [Courses.Yoshi_Circuit_T,
         Courses.Mario_Circuit_1R,
         Courses.Mario_Circuit_1T,
         Courses.New_York_Minute_R,
         Courses.New_York_Minute_RT]),
    new Item(Karts.Black_B_Dasher,
        [Courses.Mario_Circuit_T,
         Courses.Neo_Bowser_City_T,
         Courses.Yoshi_Circuit,
         Courses.Yoshi_Circuit_T,
         Courses.New_York_Minute_R,
         Courses.New_York_Minute_RT],
        [Courses.Daisy_Hills_R,
         Courses.Daisy_Hills_T,
         Courses.Neo_Bowser_City,
         Courses.Toad_Circuit_R,
         Courses.Toad_Circuit_T,
         Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_1T,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.New_York_Minute_T]),
    new Item(Karts.Yellow_Taxi,
        [Courses.Mario_Circuit_1T,
         Courses.Waluigi_Pinball,
         Courses.Toad_Circuit_R,
         Courses.New_York_Minute,
         Courses.New_York_Minute_T],
        [Courses.Yoshi_Circuit_R,
         Courses.Yoshi_Circuit_T,
         Courses.Luigis_Mansion_R,
         Courses.Toad_Circuit_T,
         Courses.Mario_Circuit_2T,
         Courses.Mario_Circuit_R,
         Courses.Neo_Bowser_City_T,
         Courses.New_York_Minute_R,
         Courses.New_York_Minute_RT]),
    new Item(Karts.Quickshaw,
        [Courses.Dino_Dino_Jungle,
         Courses.Choco_Island_2T,
         Courses.Mario_Circuit_3R,
         Courses.Paris_Promenade_R,
         Courses.Toad_Circuit,
         Courses.Mario_Circuit_T,
         Courses.Tokyo_Blur],
        [Courses.Luigis_Mansion_R,
         Courses.Mario_Circuit_2R,
         Courses.Mario_Circuit,
         Courses.Mario_Circuit_R,
         Courses.Neo_Bowser_City_T,
         Courses.Ghost_Valley_1T,
         Courses.Tokyo_Blur_R,
         Courses.Tokyo_Blur_T,
         Courses.Tokyo_Blur_RT]),
    new Item(Karts.Kabuki_Dasher,
        [Courses.Mario_Circuit_1R,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Toad_Circuit_T,
         Courses.Daisy_Hills_T,
         Courses.Daisy_Hills_T,
         Courses.Mario_Circuit_R,
         Courses.Rainbow_Road,
         Courses.Ghost_Valley_1T,
         Courses.Tokyo_Blur_RT],
        [Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_1T,
         Courses.Yoshi_Circuit_T,
         Courses.Tokyo_Blur_R,
         Courses.Tokyo_Blur_T]),
    new Item(Karts.Circuit_Special,
        [Courses.Mario_Circuit_1T,
         Courses.Yoshi_Circuit_T,
         Courses.Waluigi_Pinball_T,
         Courses.Mario_Circuit_3R,
         Courses.Toad_Circuit_R,
         Courses.Mario_Circuit_2,
         Courses.Mario_Circuit_2T,
         Courses.Mario_Circuit],
        [Courses.Mario_Circuit_1R,
         Courses.Yoshi_Circuit_R,
         Courses.Waluigi_Pinball_T,
         Courses.Toad_Circuit,
         Courses.Mario_Circuit_2R,
         Courses.Mario_Circuit_R,
         Courses.Tokyo_Blur_R]),
    new Item(Karts.Black_Circuit,
        [Courses.Yoshi_Circuit,
         Courses.Waluigi_Pinball_R,
         Courses.Neo_Bowser_City,
         Courses.Neo_Bowser_City_T,
         Courses.Rainbow_Road_R],
        [Courses.Mario_Circuit_1T,
         Courses.Cheep_Cheep_Lagoon_T,
         Courses.Shy_Guy_Bazaar_T,
         Courses.Waluigi_Pinball,
         Courses.Mario_Circuit_3,
         Courses.Mario_Circuit_2T,
         Courses.Mario_Circuit_T,
         Courses.Ghost_Valley_1T,
         Courses.Tokyo_Blur,
         Courses.Tokyo_Blur_RT]),
    new Item(Karts.Bumble_V,
        [Courses.Dino_Dino_Jungle_R,
         Courses.Waluigi_Pinball,
         Courses.Waluigi_Pinball_T,
         Courses.Mario_Circuit_3,
         Courses.Daisy_Hills],
        [Courses.Dino_Dino_Jungle_T]),
    new Item(Karts.Queen_Bee,
        [Courses.Luigis_Mansion_T,
         Courses.Toad_Circuit_R,
         Courses.Daisy_Hills_R,
         Courses.Daisy_Hills_T,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Ghost_Valley_1T,
         Courses.Paris_Promenade_RT],
        [Courses.Dino_Dino_Jungle_R,
         Courses.Luigis_Mansion,
         Courses.Mario_Circuit_3,
         Courses.Ghost_Valley_1,
         Courses.Ghost_Valley_1R]),
    new Item(Karts.Trickster,
        [Courses.Shy_Guy_Bazaar,
         Courses.Mario_Circuit_1R,
         Courses.Luigis_Mansion,
         Courses.Luigis_Mansion_R,
         Courses.Ghost_Valley_1,
         Courses.Ghost_Valley_1R],
        [Courses.Luigis_Mansion,
         Courses.Rainbow_Road_T,
         Courses.Ghost_Valley_1T]),
    new Item(Karts.Ghost_Ride,
        [Courses.Luigis_Mansion_R,
         Courses.Neo_Bowser_City,
         Courses.Neo_Bowser_City_T],
        [Courses.Luigis_Mansion,
         Courses.Luigis_Mansion_T,
         Courses.Paris_Promenade,
         Courses.Paris_Promenade_R,
         Courses.Paris_Promenade_T,
         Courses.Ghost_Valley_1,
         Courses.Ghost_Valley_1T]),
    new Item(Karts.Macharon,
        [Courses.Paris_Promenade,
         Courses.Paris_Promenade_RT],
        [Courses.Mario_Circuit_1,
         Courses.Yoshi_Circuit,
         Courses.Mario_Circuit_3T,
         Courses.Paris_Promenade_T]),
    new Item(Karts.Carrot_Kart,
        [Courses.Paris_Promenade_R,
         Courses.Paris_Promenade_T],
        [Courses.Mario_Circuit_1,
         Courses.Yoshi_Circuit,
         Courses.Mario_Circuit_3R,
         Courses.Mario_Circuit_3T,
         Courses.Paris_Promenade]),
    new Item(Karts.Badwagon,
        [Courses.Daisy_Hills_R,
         Courses.Bowsers_Castle_1,
         Courses.Kalimari_Desert,
         Courses.Neo_Bowser_City_R,
         Courses.Rock_Rock_Mountain_R,
         Courses.Yoshi_Circuit_R,
         Courses.Shy_Guy_Bazaar],
        [Courses.Bowsers_Castle_1R,
         Courses.Rock_Rock_Mountain_T]),
    new Item(Karts.Blue_Badwagon,
        [Courses.Shy_Guy_Bazaar_T,
         Courses.Mario_Circuit_3,
         Courses.Rock_Rock_Mountain_T,
         Courses.Rainbow_Road_T],
        [Courses.Shy_Guy_Bazaar,
         Courses.Luigis_Mansion_R,
         Courses.Mario_Circuit_3T,
         Courses.Paris_Promenade_T,
         Courses.Rock_Rock_Mountain,
         Courses.Daisy_Hills,
         Courses.Daisy_Hills_R,
         Courses.Neo_Bowser_City_R,
         Courses.Rainbow_Road_R,
         Courses.Ghost_Valley_1,
         Courses.New_York_Minute_RT]),
    new Item(Karts.Gold_Train,
        [Courses.Dino_Dino_Jungle_T,
         Courses.Choco_Island_2,
         Courses.Kalimari_Desert,
         Courses.Paris_Promenade],
        [Courses.Dino_Dino_Jungle,
         Courses.Waluigi_Pinball,
         Courses.Waluigi_Pinball_R,
         Courses.Paris_Promenade_R,
         Courses.Paris_Promenade_RT]),
]
var chutes = [
    new Item(Chutes.Super_Glider,
        [Courses.Mario_Circuit_1],
        [Courses.Daisy_Hills_R,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Mario_Circuit_R,
         Courses.Ghost_Valley_1,
         Courses.Toad_Circuit,
         Courses.Toad_Circuit_T,
         Courses.Yoshi_Circuit_T,
         Courses.Mario_Circuit_1T,
         Courses.Mario_Circuit_2R]),
    new Item(Chutes.Parachute,
        [Courses.Rock_Rock_Mountain_R,
         Courses.Yoshi_Circuit],
        [Courses.Dino_Dino_Jungle_R,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Kalimari_Desert_R,
         Courses.Rainbow_Road,
         Courses.Toad_Circuit,
         Courses.Yoshi_Circuit_R,
         Courses.Cheep_Cheep_Lagoon_T,
         Courses.New_York_Minute_R]),
    new Item(Chutes.Parafoil,
        [Courses.Toad_Circuit_T,
         Courses.Rock_Rock_Mountain,
         Courses.Cheep_Cheep_Lagoon],
        [Courses.Daisy_Hills,
         Courses.Daisy_Hills_R,
         Courses.Koopa_Troopa_Beach,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Rock_Rock_Mountain_T,
         Courses.Mario_Circuit_1R,
         Courses.Mario_Circuit_2T]),
    new Item(Chutes.Paper_Glider,
        [Courses.Daisy_Hills_T,
         Courses.Mario_Circuit_2,
         Courses.Mario_Circuit_2R],
        [Courses.Mario_Circuit_1,
         Courses.Yoshi_Circuit,
         Courses.Choco_Island_2,
         Courses.Choco_Island_2T,
         Courses.Luigis_Mansion_R,
         Courses.Luigis_Mansion_T,
         Courses.Waluigi_Pinball_R,
         Courses.Mario_Circuit_2T,
         Courses.Ghost_Valley_1T]),
    new Item(Chutes.Droplet_Glider,
        [Courses.Choco_Island_2,
         Courses.Choco_Island_2T],
        [Courses.Kalimari_Desert,
         Courses.Kalimari_Desert_T,
         Courses.Waluigi_Pinball,
         Courses.Toad_Circuit_R,
         Courses.Mario_Circuit_1R,
         Courses.Mario_Circuit_2R,
         Courses.Choco_Island_2R]),
    new Item(Chutes.BBIA_Parafoil,
        [Courses.Mario_Circuit_1T,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Daisy_Hills,
         Courses.Rainbow_Road_T],
        [Courses.Toad_Circuit,
         Courses.Mario_Circuit_2,
         Courses.Mario_Circuit_T,
         Courses.Rainbow_Road_R,
         Courses.Tokyo_Blur,
         Courses.Tokyo_Blur_RT,
         Courses.Paris_Promenade]),
    new Item(Chutes.Piranha_Plant_Parafoil,
        [Courses.Waluigi_Pinball_R,
         Courses.Koopa_Troopa_Beach,
         Courses.Kalimari_Desert_T],
        [Courses.Dino_Dino_Jungle_R,
         Courses.Dino_Dino_Jungle_T,
         Courses.Bowsers_Castle_1,
         Courses.Bowsers_Castle_1R,
         Courses.Waluigi_Pinball,
         Courses.Rainbow_Road]),
    new Item(Chutes.Peach_Parasol,
        [Courses.Koopa_Troopa_Beach,
         Courses.Mario_Circuit,
         Courses.Mario_Circuit_T,
         Courses.Cheep_Cheep_Lagoon_T,
         Courses.Choco_Island_2],
        [Courses.Daisy_Hills_R,
         Courses.Luigis_Mansion_R,
         Courses.Yoshi_Circuit_T,
         Courses.Mario_Circuit_1R,
         Courses.Mario_Circuit_1T,
         Courses.Cheep_Cheep_Lagoon,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.New_York_Minute_T]),
    new Item(Chutes.Flower_Glider,
        [Courses.Daisy_Hills,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.Shy_Guy_Bazaar,
         Courses.Shy_Guy_Bazaar_R],
        [Courses.Daisy_Hills_T,
         Courses.Luigis_Mansion_T,
         Courses.Toad_Circuit_R,
         Courses.Toad_Circuit_T,
         Courses.Yoshi_Circuit,
         Courses.Mario_Circuit_1R,
         Courses.New_York_Minute_RT]),
    new Item(Chutes.Oilpaper_Umbrella,
        [Courses.Dino_Dino_Jungle,
         Courses.Mario_Circuit_R,
         Courses.Rainbow_Road],
        [Courses.Kalimari_Desert_R,
         Courses.Mario_Circuit,
         Courses.Rainbow_Road_R,
         Courses.Rainbow_Road_T,
         Courses.Tokyo_Blur_R,
         Courses.Tokyo_Blur_T]),
    new Item(Chutes.Lightning_Oilpaper,
        [Courses.Shy_Guy_Bazaar,
         Courses.Kalimari_Desert,
         Courses.Kalimari_Desert_R,
         Courses.Mario_Circuit_2T,
         Courses.Neo_Bowser_City_R,
         Courses.Ghost_Valley_1T],
        [Courses.Waluigi_Pinball_T,
         Courses.Mario_Circuit_2R,
         Courses.Paris_Promenade_T,
         Courses.Paris_Promenade_RT,
         Courses.Rainbow_Road_T,
         Courses.Tokyo_Blur_RT]),
    new Item(Chutes.Bob_omb_Parafoil,
        [Courses.Dino_Dino_Jungle,
         Courses.Bowsers_Castle_1,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Toad_Circuit_R,
         Courses.Shy_Guy_Bazaar_T],
        [Courses.Bowsers_Castle_1R,
         Courses.Kalimari_Desert,
         Courses.Neo_Bowser_City_R,
         Courses.Rock_Rock_Mountain_R,
         Courses.Rock_Rock_Mountain_T,
         Courses.New_York_Minute]),
    new Item(Chutes.Shell_Parachute,
        [Courses.Daisy_Hills_T,
         Courses.Dino_Dino_Jungle_T,
         Courses.Yoshi_Circuit_R,
         Courses.Yoshi_Circuit_T],
        [Courses.Bowsers_Castle_1,
         Courses.Koopa_Troopa_Beach,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Neo_Bowser_City,
         Courses.Toad_Circuit,
         Courses.Rock_Rock_Mountain,
         Courses.Rock_Rock_Mountain_T,
         Courses.Mario_Circuit_1,
         Courses.Cheep_Cheep_Lagoon_T]),
    new Item(Chutes.Wario_Wing,
        [Courses.Neo_Bowser_City,
         Courses.Neo_Bowser_City_T,
         Courses.Luigis_Mansion,
         Courses.Waluigi_Pinball],
        [Courses.Bowsers_Castle_1T,
         Courses.Kalimari_Desert,
         Courses.Kalimari_Desert_R,
         Courses.Waluigi_Pinball_R,
         Courses.New_York_Minute_R,
         Courses.Tokyo_Blur_RT]),
    new Item(Chutes.Waluigi_Wing,
        [Courses.Bowsers_Castle_1R,
         Courses.Luigis_Mansion_R,
         Courses.Waluigi_Pinball,
         Courses.Koopa_Troopa_Beach],
        [Courses.Dino_Dino_Jungle_R,
         Courses.Dino_Dino_Jungle_T,
         Courses.Waluigi_Pinball_R,
         Courses.Rainbow_Road,
         Courses.Rainbow_Road_T]),
    new Item(Chutes.BaNaNa_Parafoil,
        [Courses.Waluigi_Pinball_T,
         Courses.Mario_Circuit_3R],
        [Courses.Choco_Island_2,
         Courses.Choco_Island_2R,
         Courses.Mario_Circuit_3,
         Courses.Paris_Promenade]),
    new Item(Chutes.Gold_Glider,
        [Courses.Koopa_Troopa_Beach_R,
         Courses.Rainbow_Road,
         Courses.Rainbow_Road_T,
         Courses.Luigis_Mansion_T,
         Courses.Toad_Circuit,
         Courses.Toad_Circuit_T,
         Courses.Mario_Circuit_1,
         Courses.Mario_Circuit_1R,
         Courses.Mario_Circuit_1T,
         Courses.New_York_Minute_RT],
        [Courses.Daisy_Hills,
         Courses.Bowsers_Castle_1T,
         Courses.Mario_Circuit,
         Courses.Cheep_Cheep_Lagoon_R,
         Courses.Choco_Island_2T,
         Courses.New_York_Minute]),
    new Item(Chutes.Fare_Flier,
        [Courses.Cheep_Cheep_Lagoon_R,
         Courses.Waluigi_Pinball_T,
         Courses.Neo_Bowser_City_T,
         Courses.New_York_Minute,
         Courses.New_York_Minute_T,
         Courses.New_York_Minute_R],
        [Courses.Mario_Circuit_1T,
         Courses.Yoshi_Circuit_R,
         Courses.Shy_Guy_Bazaar,
         Courses.Luigis_Mansion_T,
         Courses.Toad_Circuit_R,
         Courses.Mario_Circuit_2,
         Courses.Mario_Circuit_2R,
         Courses.Neo_Bowser_City,
         Courses.Ghost_Valley_1R,
         Courses.New_York_Minute_RT,
         Courses.Paris_Promenade_RT]),
    new Item(Chutes.Purple_Oilpaper_Umbrella,
        [Courses.Dino_Dino_Jungle_R,
         Courses.Mario_Circuit_3R,
         Courses.Daisy_Hills_R,
         Courses.Ghost_Valley_1R,
         Courses.Tokyo_Blur,
         Courses.Tokyo_Blur_T,
         Courses.Paris_Promenade_R],
        [Courses.Toad_Circuit,
         Courses.Daisy_Hills_T,
         Courses.Mario_Circuit_2,
         Courses.Mario_Circuit_R,
         Courses.Mario_Circuit_T,
         Courses.Ghost_Valley_1,
         Courses.Ghost_Valley_1T,
         Courses.Tokyo_Blur_R,
         Courses.Paris_Promenade,
         Courses.Paris_Promenade_RT]),
    new Item(Chutes.Full_Flight,
        [Courses.Mario_Circuit_3,
         Courses.Koopa_Troopa_Beach_T,
         Courses.Neo_Bowser_City,
         Courses.Tokyo_Blur_R,
         Courses.Tokyo_Blur_RT],
        [Courses.Cheep_Cheep_Lagoon,
         Courses.Bowsers_Castle_1,
         Courses.Waluigi_Pinball,
         Courses.Mario_Circuit_3R,
         Courses.Paris_Promenade_R,
         Courses.Daisy_Hills,
         Courses.Koopa_Troopa_Beach_R,
         Courses.Mario_Circuit_2,
         Courses.Rainbow_Road_R,
         Courses.Tokyo_Blur,
         Courses.Tokyo_Blur_T]),
    new Item(Chutes.Strawberry_Crepe,
        [Courses.Choco_Island_2R,
         Courses.Toad_Circuit,
         Courses.Paris_Promenade,
         Courses.Paris_Promenade_RT],
        [Courses.Choco_Island_2,
         Courses.Paris_Promenade_R,
         Courses.Paris_Promenade_T]),
    new Item(Chutes.Le_Tricolore,
        [Courses.Mario_Circuit_3,
         Courses.Paris_Promenade_R,
         Courses.Paris_Promenade_T],
        [Courses.Choco_Island_2,
         Courses.Mario_Circuit_3T,
         Courses.Paris_Promenade_RT]),
    new Item(Chutes.Swooper,
        [Courses.Dino_Dino_Jungle_R,
         Courses.Dino_Dino_Jungle_T,
         Courses.Bowsers_Castle_1T,
         Courses.Ghost_Valley_1,
         Courses.Ghost_Valley_1T,
         Courses.Rock_Rock_Mountain,
         Courses.Rock_Rock_Mountain_T],
        [Courses.Dino_Dino_Jungle,
         Courses.Bowsers_Castle_1,
         Courses.Bowsers_Castle_1R,
         Courses.Neo_Bowser_City_T,
         Courses.Rock_Rock_Mountain_R,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Shy_Guy_Bazaar_T,
         Courses.New_York_Minute_R]),
    new Item(Chutes.Bullet_Bill_Parachute,
        [Courses.Yoshi_Circuit_R,
         Courses.Bowsers_Castle_1,
         Courses.Rainbow_Road_R],
        [Courses.Bowsers_Castle_1R,
         Courses.Bowsers_Castle_1T,
         Courses.Shy_Guy_Bazaar,
         Courses.Shy_Guy_Bazaar_T,
         Courses.Rock_Rock_Mountain_R,
         Courses.Daisy_Hills_R,
         Courses.Koopa_Troopa_Beach,
         Courses.Kalimari_Desert_T,
         Courses.New_York_Minute_R]),
    new Item(Chutes.Cloud_Glider,
        [Courses.Yoshi_Circuit,
         Courses.Choco_Island_2R,
         Courses.Daisy_Hills_R,
         Courses.Kalimari_Desert_T,
         Courses.Mario_Circuit,
         Courses.Mario_Circuit_T,
         Courses.Neo_Bowser_City_R],
        [Courses.Shy_Guy_Bazaar,
         Courses.Shy_Guy_Bazaar_R,
         Courses.Paris_Promenade_R,
         Courses.Toad_Circuit_T,
         Courses.Rock_Rock_Mountain,
         Courses.Mario_Circuit_2T]),
    new Item(Chutes.Rainy_Balloons,
        [Courses.Luigis_Mansion_R,
         Courses.Luigis_Mansion_T,
         Courses.Waluigi_Pinball_R,
         Courses.Ghost_Valley_1R],
        [Courses.Luigis_Mansion,
         Courses.Neo_Bowser_City,
         Courses.Neo_Bowser_City_R,
         Courses.Rainbow_Road,
         Courses.Paris_Promenade_T]),
    new Item(Chutes.Wicked_Wings,
        [Courses.Yoshi_Circuit_T,
         Courses.Bowsers_Castle_1R,
         Courses.Luigis_Mansion,
         Courses.Waluigi_Pinball,
         Courses.Waluigi_Pinball_T,
         Courses.Ghost_Valley_1],
        [Courses.None]),
]

// Function to figure out what score you have
// +2 for at least 1 tier 3 on that course
// +1 for at least 1 tier 2 on that course
// +0 for anything
function GetScore(itemList) {
    var score = 0;
    
    var courses3 = [];
    var courses2 = [];

    for (var item in itemList) {
        courses3 = courses3.concat(itemList[item].courses3);
        courses2 = courses2.concat(itemList[item].courses2);
    }

    for (var key in Courses) {
        if (courses3.includes(Courses[key])) {
            score += 2;
        } else if (courses2.includes(Courses[key])) {
            score += 1;
        }
    }

    return score;
}

// What item we are trying to find improvements for?
// What items do we already have
function BestImprovement(itemListType, itemList) {
    // brute force
    // Try add item to list
    // Do calc
    // Return score
    // Array of improvements
    // Sort by biggest
    // Return
    // Can cull anything at 0
    var out = [];

    var baseScore = GetScore(itemList);

    for (var addedItem in itemListType) {
        var tempItemList = itemList.concat([itemListType[addedItem]]);
        var scoreDiff = GetScore(tempItemList) - baseScore;

        if (!itemList.includes(itemListType[addedItem])) {
            out = out.concat([scoreDiff, itemListType[addedItem]]);
        }
    }

    return out;
}

function updateItem(baseType, itemType, stringType) {
    // Figure out what is checked
    names = []
    for (var base in baseType) {
        if (document.getElementById(stringType + baseType[base]).checked) {
            names = names.concat(baseType[base]);
        }
    }

    // Get internal version of that
    myItems = [];
    for (var item in itemType) {
        if (names.includes(itemType[item].item)) {
            myItems = myItems.concat(itemType[item]);
        }
    }

    var scores = BestImprovement(itemType, myItems);

    var sortedScores = [];
    for (var i = 0; i < scores.length; i += 2) {
        var j = 0;
        for (j = 0; j < sortedScores.length; j += 2) {
            if (scores[i] > sortedScores[j]) {
                break;
            }
        }
        sortedScores.splice(j, 0, scores[i+1]);
        sortedScores.splice(j, 0, scores[i]);
    }

    // Remove old ones
    for (var i = document.getElementById(stringType + "Out").childNodes.length - 1; i >= 0; i--) {
        node = document.getElementById(stringType + "Out").childNodes[i];
        document.getElementById(stringType + "Out").removeChild(node);
    }

    // Add new ones
    for (var i = 0; i < sortedScores.length; i += 2) {
        var row = document.createElement("tr");
        var score = document.createElement("th");
        var name = document.createElement("th");

        row.setAttribute("align", "left");

        score.appendChild(document.createTextNode(sortedScores[i]))
        name.appendChild(document.createTextNode(sortedScores[i+1].item))
        row.appendChild(score);
        row.appendChild(name);
        document.getElementById(stringType + "Out").append(row);
    }
}

function updateDrivers() {
    updateItem(Drivers, drivers, "drivers");
}

function updateKarts() {
    updateItem(Karts, karts, "karts");
}

function updateChutes() {
    updateItem(Chutes, chutes, "chutes");
}

function addCheckBoxes(baseType, stringPrefix, cbfunc) {
    for (var type in baseType) {
        var pair = baseType[type];
        var label = document.createElement("label")
        var description = document.createTextNode(pair);
        var checkbox = document.createElement("input")
        checkbox.type = "checkbox"
        checkbox.id = stringPrefix + pair;
        checkbox.onclick = cbfunc;

        label.appendChild(checkbox);
        label.appendChild(description);
        document.getElementById(stringPrefix).appendChild(label);
        document.getElementById(stringPrefix).appendChild(document.createElement("br"));
    }
}

addCheckBoxes(Drivers, "drivers", updateDrivers);
addCheckBoxes(Karts, "karts", updateKarts);
addCheckBoxes(Chutes, "chutes", updateChutes);

updateDrivers();
updateKarts();
updateChutes();